### ISSUE TITLE
Installer should be more informative

### ISSUE THREAD

**Issue by deri82** [linuxmint/mintinstall#100]
I did mint 17.1 install just recently and I have 17.2 installer but for some it wasnt able to install. 

There are some options like crypting home. Then there is LVM option or something like that. I don't even remember the exact name currently. I have never used it during install time, because I don't know what it does.

Also during partions, it could be more informative about what /boot /swap etc are.

**Comment by xenopeek** [comment]
mintinstall is the Software Manager program so this issue is reported in the wrong place. This issue should be closed.

A better place to ask for support with analyzing issues with installation of Linux Mint is the Installation & Boot section on the forums https://forums.linuxmint.com/viewforum.php?f=46. Suggestions for improving the installation of Linux Mint can be made on the Suggestions & New Ideas section on the forums https://forums.linuxmint.com/viewforum.php?f=29.
