### ISSUE TITLE
Add support for uninstalling dependencies

### ISSUE THREAD

**Issue by AsciiWolf** [linuxmint/mintinstall#159]
It looks like that mintinstall does not uninstall unnecessary dependencies when uninstalling an application. They can be removed manually by running _apt autoremove_, but I think that mintinstall itself should do this.

**Comment by happyniko** [comment]
You're right. Uninstalling unnecessary dependencies through mintinstall is a good improvement. But with 18.3, mintinstall doesn't mark **necessary dependencies** anymore, when you remove packages. Through this it's possible to destroy your system because of unwanted removals. - Therefore it's still the safest option for me to use 17.3…

**Comment by snacaman** [comment]
This will be great improvement. Mintinstall should remove unnecessary dependencies and configuration files to keep system clean. This could be an options in the configuration panel for more advanced users. Removing package should work similar to apt-get --purge autoremove package. Additionally it could display a confirmation request with list of packages when removing dependencies like apt does. That request could have a checkboxes to override main configuration preferences.

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by AsciiWolf** [comment]
Support for autoremoving dependencies was recently [added](https://github.com/hughsie/PackageKit/pull/254) into PackageKit and will be enabled in Ubuntu.
