### ISSUE TITLE
Software Manager 18.3 displayes wrong (Package-) sizes using search-feature

### ISSUE THREAD

**Issue by orcus-de** [linuxmint/mintinstall#168]
Reported by a user in #linuxmint-help + double-checked myself
Software Manager 18.3 displayes wrong (Package-) sizes using search-feature: (displays size of recently manually selected package)

Expected: using the search-feature should display the correct sizes for a package.

Tested on: mint 18-3 cinnamon 64bit

Steps to reproduce - start software manager
1) manually select graphics->blender for install (don't use search-option)
(displayed) Size: 33MB to download; 148MB of disk space required
(don't install blender...)

2) (while still being on the blender install-page) enter "gparted" in search field on top-right: select gparted from result-list
(displayed) Size: 33MB to download; 148MB of disk space required (=blender)
correct sizes would be: 457KB/2MB

3) Install gparted (accept additional dependencies displayed)
Install start, Launch is available - gparted does start as expected

Additional reported issues: besides the given steps-to-reproduce here the displayed size seems to accumulate previous sizes being used (not tested/veryfied myself)

**Comment by al-mission-2016** [comment]
I also confirm the problem.
It seems that the variables (in python) that keep the size of app is not zeroed when new page (with app info) is shown. So if last size was say 200 mb then when a user opens new page the app size =
max (old_app_size, new_app_size).
=> the apparent app-size is only growing.

Somebody forget to reset vars before using them (?), e.g.
    downloadSize = 0
    required_space = 0
: )

Besides, there is no info about sizes of flatpack apps at all.

**Comment by xenopeek** [comment]
Retesting with mintinstall master, we believe this issue to have been fixed by https://github.com/linuxmint/mintinstall/commit/c0af8edddae52de44a67830ed81378c943c2dd34.

To reproduce the issue I first did this testcase:

1. browse to Graphics > 3D > Blender and see size: 57MB to download, 219MB of disk space required
2. search for Gedit and see size: 58MB to download, 224MB of disk space required
3. restart Software Manager
4. search for Gedit and see size: 536KB to download, 4MB of disk space required

So (account for some rounding) indeed package sizes of previous packages were added up to the current package you looked at.

After installing mintinstall master (and new dependency python3-configobj) the testcase shows the package sizes are no longer added up and shown correctly.
