### ISSUE TITLE
It is unclear how to install the popular program Dropbox

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintinstall#221]
In the Software Manager, and Synaptics, one is offered (1) a version of Dropbox with 'nautilus' and 'Gnome' integration, (2) 'nemo-dropbox'. The former can't be right for Mint Cinnamon. The latter looks like merely a front-end.

There is, however, [this](https://www.dropbox.com/install-linux), which is what I will try. EDIT: The installer offered by the Dropbox website advertises itself as 1. So the problem seems to be with the packaging DropBox provides - though it would be nice were the Software Manager to correct that problem.

EDIT: When I run the installer from the website - which, as said, is one of the packages Mint offers - I get this:

![image](https://user-images.githubusercontent.com/9998846/49680612-6a44e480-fa8e-11e8-971d-0edc360798ad.png)

although clicking 'OK' does, without much warning, download the (main) missing component. Then when one tries to run Dropbox, in X, nothing happens - though trying it in the terminal generates a message about needing to register a dropbox account.

This is all a terrible mess.

**Comment by CottonEaster** [comment]
And after all that - and grimness with ReCapchas (which I mention because it will be part of the experience of the hapless person who tries to install Dropbox on Mint) Dropbox still will not run - though I suppose I should create a separate bug report for that - [except that someone has already](https://github.com/linuxmint/Cinnamon/issues/2846). I hope this problem, which seems to be an icon problem, is fixed in the version of Cinnamon that ships with Mint 19.1

**Comment by xenopeek** [comment]
To any future readers: `dropbox` is the package needed to get Dropbox installed on your system, the other `dropbox-*` packages are to add integration with your file manager.

![image](https://user-images.githubusercontent.com/21159972/82752434-47130f80-9dbe-11ea-8e24-703d531be11a.png)
