### ISSUE TITLE
lose install log and remove log for Marker on mintinstall 7.9.7

### ISSUE THREAD

**Issue by chrisju** [linuxmint/mintinstall#246]
I install Marker by mintinstall. It showed that cost 2G+ disk space. I tried and uninstalled it by mintinstall, then free 60M+ disk space. I run "apt autoremove" but nothing removed. Then i check the /var/log/apt/history.log and /var/log/dpkg.log but not found log for Marker. Another software's log(Retext)  is OK.

**Comment by gm10** [comment]
That's working as intended for flatpaks. The first time you install one the required platform package(s) gets installed as well, that's why the install was so big. When you remove it again the platform stays in place, otherwise you'd have to reinstall it again the next time you install a flatpak package.

You can manually remove it using this command if you're sure you won't need it anymore:
`flatpak uninstall --unused`
