### ISSUE TITLE
[Mint 21.1 MATE] Live session - cannot successfully install Nemo

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mintinstall#354]
Simply put, in a live session of Mint 21.1 MATE, you cannot successfully install Nemo:

[mintinstall.webm](https://user-images.githubusercontent.com/11896003/211701307-eaac6b83-b652-406d-ad92-aed8ab334801.webm)

**Comment by umikali222** [comment]
don't you have nemo already installed? And if you no longer need help, close the question.

**Comment by NintendoManiac64** [comment]
> don't you have nemo already installed

If that were the case, then the software manager would display "Open" and "Remove" buttons rather than an "Install" button.

**Comment by umikali222** [comment]
oh, so already sometime ago, I tried installing cheese on an xfce live session (don't ask why) and I think on live sessions, you can't install software (at least trough software manager), probably because you would have to either store the app in memory, or fetch all the data from the cloud. so I think it's disabled on purpose.

**Comment by umikali222** [comment]
oh, and I think you can install it with `sudo apt install nemo`

**Comment by mtwebster** [comment]
You can install software in the live session -

The original issue is because a new version of nemo had been released since the ISO was made, so the package cache that came with the iso wasn't up-to-date.
