### ISSUE TITLE
Software Manager (mintinstall) slow launching

### ISSUE THREAD

**Issue by Angedestenebres** [linuxmint/mintinstall#386]
Hello,

After the upgrade from 21.1 to 21.2 I noticed that the launching of the Software Manager is slow as said on the forum [here](https://forums.linuxmint.com/viewtopic.php?p=2350707#p2350707).

My computer is a new one but the setup is correct for my daily needs and it works well, however, the software manager needs a lot of time to be launched, around 13 seconds.
Information about the setup: i5-5300U (4) @ 2.900GHz / 8Go RAM / SSD Crucial BX500 480 Go.

After asking to some people, it seems that not all users have the same experience with the software manager so I tried to delete the cache in /home/username/.cache/mintinstall. After that the launching was fast even if cache has to be created again but after closing/opening it again, the issue was back...

I tried to see in Terminal if there was an explanation but all is fine from my point of view:

![image](https://github.com/linuxmint/mintinstall/assets/21110485/77cc8182-3f50-421d-b630-87db32c77e65)

So my next step was to try with another computer (an older one) and I confirm that I have exactly the same issue, the launching is slow... Here is the second setup: Intel i5-3230M (4) @ 3.200GHz / 4 Go RAM / SSD 32 Go.

In order to understand the issue, I make a video capture that I posted on Peertube: https://video.tedomum.net/w/2WL84RnHbnaSXXcQGzGSg3
Of course, with the older version of the software manager provided on Mint 21.1, it was faster :)

Do you know how to improve that?

Thanks in advance.

**Comment by mtwebster** [comment]
This isn't really new - it was pretty slow in previous versions as well.

The reason it's faster after deleting the cache is because at startup, mintinstall discovers it needs to rebuild the cache, and that is able to be done asynchronously while the window is allowed to load and display its 'refreshing cache' message.

Once the cache is up-to-date, subsequent launches must load that cache completely *before* displaying the window. Loading and processing that file is computationally expensive, so there's a delay.

We would like the window to open immediately, regardless, but it would still have to finish loading that cache before packages could be displayed.

So no matter what, startup will be slow, the difference is the user experience while this is happening.

Up until now, there was a significant startup delay, but mostly tolerable (not yet worth the effort of reworking things to address it). When this was all originally done, the delay was trivial, which is the reason this design flaw was allowed to exist. But as flatpaks become more popular, and as we make under-the-hood changes to mintinstall, this delay has increased (it *is* bad now, I agree). We'll have a look at improving this.

**Comment by LinuxOnTheDesktop** [comment]
On Mint 21.2, and the latest flatpak, mintinstall is still very slow - especially on battery power (> 10 seconds on a quad-core laptop with 16GM RAM and M2 SSD!). This is bad, because the user can worry that something is broken. Note also that many a user _new to Mint_ will be using the 'Software Manager'.

**Comment by spamegg1** [comment]
It's a total of 14 seconds here: first it does not even show up for 10 seconds, then it shows up, then it freezes for 4 seconds, after which the images are refreshed and it's usable again.

Without Flatpak / Flathub installed / enabled, it's much much faster, 1-2 seconds.

This is coming up over and over again on the Forums. Can we please prioritize this @mtwebster ?

**Comment by Dan-cer** [comment]
Also here it is much slower in LM 21.3 than in 20.3, both Cinnamon (about 30 secs). After removing flatpak options it got much faster, even faster than @spamegg1 wrote above.

**Comment by bernd-wechner** [comment]
I find it painfully a slow and causes confusion as it's not clear it's been started. I think for a UX perspective a splash screen is a must. Display immediately that it's loading the cache, so I know I'm waiting for it, and I didn't misclick when I tried to start it and end up starting a second ...

**Comment by clefebvre** [comment]
Fixed on git master.
