### ISSUE TITLE
window title does not indicate when remote

### ISSUE THREAD

**Issue by sjsepan3** [linuxmint/mintinstall#388]
Type:
Feature request

Description:
Window titlebar does not show "Software Manager (on remotemachinename)" when SSH'ed to remote machine and executing  mintinstall.  Apps that do include nemo, mintupdate, cinnamon-settings.

Expected:
Titlebar of remote GUI app mintinstall shows title with the format like 'appname (as remotemachinename)' when run remotely with 'ssh -X '.

Observed:
Titlebar  of remote GUI app mintinstall shows app name only, even though it starts remotely.

Environment:
Linux Mint 21.2 Cinnamon

**Comment by mtwebster** [comment]
Unfortunately this is due to mintinstall using a different type of window (client-decorated) that provides its own titlebar and controls the title text entirely. The app itself is unaware that it's running remotely.

You can probably reproduce this with a few other Mint apps - mintwelcome and warpinator, for example.

On the other hand, those other apps - nemo, mintupdate, etc... have their titlebar provided by the window manager which *is* aware that a window is remote, and adds the "(on remotemachine)" text to the window title.

I'm really not sure there's anything we can do about this short of reworking the UI of these apps to not use client-decorations - this issue isn't something we were aware of until now.

**Comment by sjsepan3** [comment]
Thank You for looking into the cause -- whether you decide to pursue it or not, at least its known.
