### ISSUE TITLE
[Feature Request]: Add support for snap apps

### ISSUE THREAD

**Issue by Deewens** [linuxmint/mintinstall#418]
I know that the Mint team is pretty much against Snap, and I can understand why. However, some user does not really care about that, and just want to be able to install every possible packages, and unfortunately, the Linux space is still divided between deb/rpm, AppImages, flatpak and Snap, which is quite annoying!

Linux Mint is targeted at beginners or people that does not want to tinker too much with their system. I think it would be beneficial to add support for snap package in the Software Manager, which would be of course an opt-in features. This would allow the user to not have to install the graphical Snap Store from Ubuntu, and only use one GUI Store. Furthermore, lambda users does not necessarily know or care about the difference between snaps and others things, and just want their system to work, myself included, even though I know how to use the CLI, and such, I like GUI apps. Unfortunately, some software packages are only available through Snaps, or just better supported in Snap, although, a lot of the time, a .deb package is also provided, .deb does not integrate well with the system package manager, and neither AppImages.

As I said, this would only be opt-in, and I understand why the team does not really like Snap.

**Comment by InvisibleRasta** [comment]
gnome-software with the gnome-software-plugin-snap would do the trick

**Comment by clefebvre** [comment]
People have the right to disagree and/or to not care. It's important that users are able to do what they want with THEIR computer. That's why we wrote documentation and made it easy for them to re-enable snap.

Past that, we won't spend resources in developing or promoting something we disagree with, recommend against and that could disappear overnight if Canonical felt they didn't get the return they expected on their investment.
