### ISSUE TITLE
mint install cant run

### ISSUE THREAD

**Issue by alen-sherif** [linuxmint/mintinstall#82]
alen@alen-LinuxMint ~ $ mintinstall
add_categories took 1.141 ms
build_matched_packages took 0.221 ms
add_packages took 3227.170 ms
add_reviews took 1025.718 ms
__init__ took 5301.869 ms
Aborted
to unlock mutex that was not locked

**Comment by monsta** [comment]
That's caused by adding some questionable PPAs like [this one](https://launchpad.net/~ricotz/+archive/ubuntu/testing) and upgrading GLib from 2.40 to 2.42 or newer from there. This is not a safe thing to do.

Revert your GLib packages to 2.40 to get rid of this issue.

Another way to fix it is available at https://github.com/linuxmint/mintinstall/pull/75.

**Comment by dacoex** [comment]
OK, I identified the issue:

I had tried out soem packages from Elementary OS daily PPA:
https://launchpad.net/~elementary-os/+archive/ubuntu/daily

After a 
```
sudo ppa-purge ppa:elementary-os/daily
```
the normal packages are being brought back. 
I hope this helps others, too.

See also:
http://www.linuxmintusers.de/index.php?PHPSESSID=a8b001c95d03f26ed2baffacc9ff921d&topic=24475.msg320525#msg320525

**Comment by timmie** [comment]
this also applies to 
https://launchpad.net/~elementary-os/+archive/ubuntu/daily

fix the problem.
```
sudo ppa-purge ppa:elementary-os/daily
```
