### ISSUE TITLE
after installing fully encrypted: swap is not working at all

### ISSUE THREAD

**Issue by edmundlaugasson** [linuxmint/mintinstall#85]
Currently when installing Linux Mint with fully encrypted disk - swap is not working at all. This should be know issue but could not find it. But problem in Linux Mint 17.1 still persist.

**Comment by xenopeek** [comment]
mintinstall is the Software Manager program so this issue is reported in the wrong place. This issue should be closed.

A better place to ask for support with analyzing issues with installation of Linux Mint is the Installation & Boot section on the forums https://forums.linuxmint.com/viewforum.php?f=46.
