### ISSUE TITLE
Mintinstall Waiting - Multiple Consecutive Installation

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mintinstall#86]
Mintinstall goes to waiting after a while and can not continue when install multiple application.

http://www.paste.org/78562

**Comment by AXDOOMER** [comment]
Here it says there are four ongoing actions and there is three packages to install. I wanted to install seven packages but it got stuck there forever. I've been using Linux Mint since version 16 and it always had this problem. 

![screenshot from 2015-06-25 21 20 38](https://cloud.githubusercontent.com/assets/6194072/8387028/5a977644-1c23-11e5-985e-0d806fc259d0.png)

**Comment by clefebvre** [comment]
Backend moved to aptdaemon on git master.
